In [1]:
import torch
import numpy as np
import cv2

In [2]:
model = torch.hub.load('ultralytics/yolov5', 'yolov5s', pretrained=True)

Using cache found in /home/tal/.cache/torch/hub/ultralytics_yolov5_master
YOLOv5 🚀 2021-12-23 torch 1.10.1+cpu CPU

Fusing layers... 
Model Summary: 213 layers, 7225885 parameters, 0 gradients
Adding AutoShape... 


In [3]:
frame = 'runs/detect/exp/zidane.jpg'
results = model(frame)

/home/tal/virtualenv_environments/py38_yolov5_pytorch/lib/python3.8/site-packages/torch/autocast_mode.py:141: UserWarning: User provided device_type of 'cuda', but CUDA is not available. Disabling
  warnings.warn('User provided device_type of \'cuda\', but CUDA is not available. Disabling')


In [4]:
labels = results.xyxyn[0][:, -1].numpy() # all rows last column
labels

array([          0,           0,          27], dtype=float32)

In [5]:
cord = results.xyxyn[0][:, :-1].numpy() # all rows all columns except last
cord

array([[    0.10966,     0.28242,     0.57098,     0.98778,     0.93423],
       [    0.59002,    0.057221,      0.8837,     0.99742,     0.90169],
       [    0.34217,      0.5848,     0.40061,      0.9898,     0.55637]], dtype=float32)

In [6]:
classes = model.names
classes

['person',
 'bicycle',
 'car',
 'motorcycle',
 'airplane',
 'bus',
 'train',
 'truck',
 'boat',
 'traffic light',
 'fire hydrant',
 'stop sign',
 'parking meter',
 'bench',
 'bird',
 'cat',
 'dog',
 'horse',
 'sheep',
 'cow',
 'elephant',
 'bear',
 'zebra',
 'giraffe',
 'backpack',
 'umbrella',
 'handbag',
 'tie',
 'suitcase',
 'frisbee',
 'skis',
 'snowboard',
 'sports ball',
 'kite',
 'baseball bat',
 'baseball glove',
 'skateboard',
 'surfboard',
 'tennis racket',
 'bottle',
 'wine glass',
 'cup',
 'fork',
 'knife',
 'spoon',
 'bowl',
 'banana',
 'apple',
 'sandwich',
 'orange',
 'broccoli',
 'carrot',
 'hot dog',
 'pizza',
 'donut',
 'cake',
 'chair',
 'couch',
 'potted plant',
 'bed',
 'dining table',
 'toilet',
 'tv',
 'laptop',
 'mouse',
 'remote',
 'keyboard',
 'cell phone',
 'microwave',
 'oven',
 'toaster',
 'sink',
 'refrigerator',
 'book',
 'clock',
 'vase',
 'scissors',
 'teddy bear',
 'hair drier',
 'toothbrush']

In [7]:
results.pandas().xyxy

[         xmin        ymin         xmax        ymax  confidence  class    name
 0  140.368683  203.339432   730.849976  711.201965    0.934227      0  person
 1  755.224731   41.199127  1131.141113  718.141235    0.901689      0  person
 2  437.977570  421.055054   512.774658  712.656982    0.556367     27     tie]

In [8]:
results.pandas().xyxy[0]

xmin        ymin         xmax        ymax  confidence  class    name
0  140.368683  203.339432   730.849976  711.201965    0.934227      0  person
1  755.224731   41.199127  1131.141113  718.141235    0.901689      0  person
2  437.977570  421.055054   512.774658  712.656982    0.556367     27     tie

In [9]:
results.xyxyn

[tensor([[ 0.10966,  0.28242,  0.57098,  0.98778,  0.93423,  0.00000],
         [ 0.59002,  0.05722,  0.88370,  0.99742,  0.90169,  0.00000],
         [ 0.34217,  0.58480,  0.40061,  0.98980,  0.55637, 27.00000]])]

In [10]:
results.xyxyn[0]

tensor([[ 0.10966,  0.28242,  0.57098,  0.98778,  0.93423,  0.00000],
        [ 0.59002,  0.05722,  0.88370,  0.99742,  0.90169,  0.00000],
        [ 0.34217,  0.58480,  0.40061,  0.98980,  0.55637, 27.00000]])

In [11]:
results.pandas().xyxyn

[       xmin      ymin      xmax      ymax  confidence  class    name
 0  0.109663  0.282416  0.570977  0.987781    0.934227      0  person
 1  0.590019  0.057221  0.883704  0.997418    0.901689      0  person
 2  0.342170  0.584799  0.400605  0.989801    0.556367     27     tie]

In [12]:
results.pandas().xyxyn[0]

xmin      ymin      xmax      ymax  confidence  class    name
0  0.109663  0.282416  0.570977  0.987781    0.934227      0  person
1  0.590019  0.057221  0.883704  0.997418    0.901689      0  person
2  0.342170  0.584799  0.400605  0.989801    0.556367     27     tie

In [15]:
image = cv2.imread(frame)
x_shape, y_shape = image.shape[1], image.shape[0]
x_shape, y_shape

(1280, 720)

In [16]:
0.109663*1280

140.36864

In [17]:
results.xyxy.numpy()

AttributeError: 'list' object has no attribute 'numpy'

In [18]:
results.xyxy[0].numpy()

array([[     140.37,      203.34,      730.85,       711.2,     0.93423,           0],
       [     755.22,      41.199,      1131.1,      718.14,     0.90169,           0],
       [     437.98,      421.06,      512.77,      712.66,     0.55637,          27]], dtype=float32)

In [23]:
cord = results.xyxy[0].numpy()
target_cord = cord[cord[:,5]==0 and cord[:, 4]>0.92]
target_cord

SyntaxError: invalid syntax (3615485654.py, line 2)

In [27]:
cord = results.xyxy[0].numpy()
target_cord = list(filter(lambda row: row[5]==0 and row[4]>0.92, cord))
target_cord

[]

In [28]:
cord = results.xyxy[0].numpy()
target_cord = cord[cord[:,5]==0]
target_cord = target_cord[target_cord[:, 4]>0.92]
target_cord

array([[     140.37,      203.34,      730.85,       711.2,     0.93423,           0]], dtype=float32)

In [29]:
target_cord[:, :2]

array([[     140.37,      203.34]], dtype=float32)

In [31]:
target_cord[:, :2][0]

array([     140.37,      203.34], dtype=float32)

In [32]:
target_cord[:, :2][0][0]

140.36868

In [33]:
target_cord[0][0]

140.36868

In [34]:
target_cord[0][1]

203.33943

In [35]:
cord = results.xyxy[0].numpy()
target_cord = cord[cord[:,5]==0]
target_cord = target_cord[target_cord[:, 4]>0.6]
target_cord

array([[     140.37,      203.34,      730.85,       711.2,     0.93423,           0],
       [     755.22,      41.199,      1131.1,      718.14,     0.90169,           0]], dtype=float32)

In [36]:
target_cord[0][0]

140.36868

In [38]:
target_cord = cord[cord[:,5]==0]
target_cord

array([[     140.37,      203.34,      730.85,       711.2,     0.93423,           0],
       [     755.22,      41.199,      1131.1,      718.14,     0.90169,           0]], dtype=float32)

In [39]:
len(target_cord)

2

In [40]:
target_cord = cord[cord[:,5]==3]
target_cord

array([], shape=(0, 6), dtype=float32)

In [44]:
len(target_cord)

0

In [ ]:
frame = 'runs/detect/exp/zidane.jpg'
image = cv2.imread(frame)
while True:
    cv2.imshow('frame', image)
    if cv2.waitKey(1) == ord('q'):
        break

cv2.destroyAllWindows()

In [ ]:

results.print()

In [ ]:
x = results.save()  # or .show()
print(f'x={x}')

In [ ]:
x = results.show()
print(f'x={x}')

In [ ]:
 results.xyxy[0]

In [ ]:
while True:
    cv2.imshow('result', np.asarray(results.imgs[0], dtype=np.uint8))
    if cv2.waitKey(1) == ord('q'):
        break

cv2.destroyAllWindows()

In [ ]:
while True:
    cv2.imshow('result', results.imgs[0])
    if cv2.waitKey(1) == ord('q'):
        break

cv2.destroyAllWindows()

In [16]:
while True:
    cv2.imshow('result', image)
    if cv2.waitKey(1) == ord('q'):
        break

cv2.destroyAllWindows()

In [ ]:
print(f'results.pandas().xyxy[0]:\n{results.pandas().xyxy[0]}')

In [ ]:
results

In [ ]:
cv2.imshow('result', frame)

In [2]:
model = torch.hub.load('ultralytics/yolov5', 'yolov5s', pretrained=True)
frame = 'runs/detect/exp/zidane.jpg'
image = cv2.imread(frame)

device = 'cuda' if torch.cuda.is_available() else 'cpu'
model.to(device)

Using cache found in /home/tal/.cache/torch/hub/ultralytics_yolov5_master
YOLOv5 🚀 2021-12-23 torch 1.10.1+cpu CPU

Fusing layers... 
Model Summary: 213 layers, 7225885 parameters, 0 gradients
Adding AutoShape... 


AutoShape(
  (model): DetectMultiBackend(
    (model): Model(
      (model): Sequential(
        (0): Conv(
          (conv): Conv2d(3, 32, kernel_size=(6, 6), stride=(2, 2), padding=(2, 2))
          (act): SiLU(inplace=True)
        )
        (1): Conv(
          (conv): Conv2d(32, 64, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
          (act): SiLU(inplace=True)
        )
        (2): C3(
          (cv1): Conv(
            (conv): Conv2d(64, 32, kernel_size=(1, 1), stride=(1, 1))
            (act): SiLU(inplace=True)
          )
          (cv2): Conv(
            (conv): Conv2d(64, 32, kernel_size=(1, 1), stride=(1, 1))
            (act): SiLU(inplace=True)
          )
          (cv3): Conv(
            (conv): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1))
            (act): SiLU(inplace=True)
          )
          (m): Sequential(
            (0): Bottleneck(
              (cv1): Conv(
                (conv): Conv2d(32, 32, kernel_size=(1, 1), stride=(1, 1))
           

In [31]:
"""
The function below identifies the device which is availabe to make the prediction and uses it to load and infer the frame. Once it has results it will extract the labels and cordinates(Along with scores) for each object detected in the frame.
"""
def score_frame(frame, model):
    #frame = [torch.tensor(frame)]
    results = model(frame)
    labels = results.xyxyn[0][:, -1].numpy()
    cord = results.xyxyn[0][:, :-1].numpy()
    return labels, cord

In [46]:
"""
The function below takes the results and the frame as input and plots boxes over all the objects which have a score higer than our threshold.
"""
def plot_boxes(results, frame):
    labels, cord = results
    n = len(labels)
    x_shape, y_shape = frame.shape[1], frame.shape[0]
    for i in range(n):
        row = cord[i]
        # If score is less than 0.2 we avoid making a prediction.
        if row[4] < 0.2: 
            continue
        x1 = int(row[0]*x_shape)
        y1 = int(row[1]*y_shape)
        x2 = int(row[2]*x_shape)
        y2 = int(row[3]*y_shape)
        bgr = (0, 255, 0) # color of the box
        classes = model.names # Get the name of label index
        label_font = cv2.FONT_HERSHEY_SIMPLEX #Font for the label.
        cv2.rectangle(frame, \
                      (x1, y1), (x2, y2), \
                       bgr, 2) #Plot the boxes
        cv2.putText(frame,\
                    classes[int(labels[i])], \
                    (x1, y1), \
                    label_font, 0.9, bgr, 2) #Put a label over box.
        return frame

In [47]:

while True:
    result = score_frame(frame, model)
    labeled_img = plot_boxes(result, image)
    cv2.imshow('result', np.asarray(labeled_img, dtype=np.uint8))
    if cv2.waitKey(1) == ord('q'):
        break

cv2.destroyAllWindows()

/home/tal/virtualenv_environments/py38_yolov5_pytorch/lib/python3.8/site-packages/torch/autocast_mode.py:141: UserWarning: User provided device_type of 'cuda', but CUDA is not available. Disabling
  warnings.warn('User provided device_type of \'cuda\', but CUDA is not available. Disabling')
/home/tal/virtualenv_environments/py38_yolov5_pytorch/lib/python3.8/site-packages/torch/autocast_mode.py:141: UserWarning: User provided device_type of 'cuda', but CUDA is not available. Disabling
  warnings.warn('User provided device_type of \'cuda\', but CUDA is not available. Disabling')
/home/tal/virtualenv_environments/py38_yolov5_pytorch/lib/python3.8/site-packages/torch/autocast_mode.py:141: UserWarning: User provided device_type of 'cuda', but CUDA is not available. Disabling
  warnings.warn('User provided device_type of \'cuda\', but CUDA is not available. Disabling')
/home/tal/virtualenv_environments/py38_yolov5_pytorch/lib/python3.8/site-packages/torch/autocast_mode.py:141: UserWarning: U

/home/tal/virtualenv_environments/py38_yolov5_pytorch/lib/python3.8/site-packages/torch/autocast_mode.py:141: UserWarning: User provided device_type of 'cuda', but CUDA is not available. Disabling
  warnings.warn('User provided device_type of \'cuda\', but CUDA is not available. Disabling')
/home/tal/virtualenv_environments/py38_yolov5_pytorch/lib/python3.8/site-packages/torch/autocast_mode.py:141: UserWarning: User provided device_type of 'cuda', but CUDA is not available. Disabling
  warnings.warn('User provided device_type of \'cuda\', but CUDA is not available. Disabling')
/home/tal/virtualenv_environments/py38_yolov5_pytorch/lib/python3.8/site-packages/torch/autocast_mode.py:141: UserWarning: User provided device_type of 'cuda', but CUDA is not available. Disabling
  warnings.warn('User provided device_type of \'cuda\', but CUDA is not available. Disabling')
/home/tal/virtualenv_environments/py38_yolov5_pytorch/lib/python3.8/site-packages/torch/autocast_mode.py:141: UserWarning: U

In [48]:
result = score_frame(frame, model)
labeled_img = plot_boxes(result, image)
out.write(labeled_img)

/home/tal/virtualenv_environments/py38_yolov5_pytorch/lib/python3.8/site-packages/torch/autocast_mode.py:141: UserWarning: User provided device_type of 'cuda', but CUDA is not available. Disabling
  warnings.warn('User provided device_type of \'cuda\', but CUDA is not available. Disabling')


NameError: name 'out' is not defined